### ISSUE TITLE
Add a Twitter Clone

### ISSUE THREAD

**Issue by AnuragM23** [arindal1/yolov5-onnx-object-recognition#26]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Want a simple twitter clone(or X Clone) using either any web dev framework.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by arindal1** [comment]
@AnuragM23 if you have already completed it, add it 👍🏼
